name: " Manage Repository Permissions"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Link of the repository"
        required: true
        type: string
      permission:
        description: "Permission level"
        required: true
        default: "read"
        options:
          - read
          - write
          - admin
      team:
        description: "GitHub team name"
        required: true
        type: string

permissions:
  contents: write
  members: write

jobs:
  update-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB1234 }}
      run: echo $GITHUB1234 | gh auth login --with-token

    - name: Extract repository owner and name
      id: extract_repo
      run: |
        REPO_URL="${{ inputs.repository }}"
        REPO_URL=${REPO_URL#https://github.com/}
        OWNER=$(echo $REPO_URL | cut -d'/' -f1)
        REPO=$(echo $REPO_URL | cut -d'/' -f2)
        echo "::set-output name=owner::$OWNER"
        echo "::set-output name=repo::$REPO"

    - name: Add team to repository with specified permissions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB1234 }}
      run: |
        OWNER=${{ steps.extract_repo.outputs.owner }}
        REPO=${{ steps.extract_repo.outputs.repo }}
        TEAM=${{ inputs.team }}
        PERMISSION=${{ inputs.permission }}
        
        gh api \
          --method PUT \
          -H "Accept: application/vnd.github.v3+json" \
          "/orgs/$OWNER/teams/$TEAM/repos/$OWNER/$REPO" \
          -f permission="$PERMISSION"
